require("__Crystarion__.prototypes.offence.ammo")
require("__Crystarion__.prototypes.offence.ammo_high_explosive")
require("__Crystarion__.prototypes.offence.land_mine")
require("__Crystarion__.prototypes.offence.projectile_turret")
require("__Crystarion__.prototypes.offence.projectile_alternate")
require("__Crystarion__.prototypes.offence.projectile")