require("__Crystarion__.prototypes.entities.crusher")
require("__Crystarion__.prototypes.entities.crystalizer")
require("__Crystarion__.prototypes.entities.energizer")
require("__Crystarion__.prototypes.entities.rock")
require("__Crystarion__.prototypes.entities.generator")