require("__Crystarion__.prototypes.entities.crusher")
require("__Crystarion__.prototypes.entities.crystalizer")
require("__Crystarion__.prototypes.entities.energizer")
require("__Crystarion__.prototypes.entities.generator")
require("__Crystarion__.prototypes.entities.resource")
require("__Crystarion__.prototypes.entities.resourceCollector")