@startuml

hide methods
hide fields
hide circle

[Crystal] as C #lightpink
[Water] as W #lightpink

[Red Crystal] as RC #lightgreen
[Green Crystal] as GC #lightgreen
[Blue Crystal] as BC #lightgreen
[Crushed Crystal] as CCr #lightgreen
[Plasma] as PA #lightgreen

package Energizer #lightyellow {
package "Green Split Flow" {
[Split Green] as SG #lightblue
[Split Magenta] as SM #lightblue
[Magenta Crystal] as MC
[Red Crystal] as RC1
[Green Crystal] as GC1
[Blue Crystal] as BC1
}
package "Red Split Flow" {
[Split Red] as SR #lightblue
[Split Cyan] as SC #lightblue
[Cyan Crystal] as CC
[Red Crystal] as RC2
[Green Crystal] as GC2
[Blue Crystal] as BC2

}
package "Blue Split Flow" {
[Split Blue] as SB #lightblue
[Split Yellow] as SY #lightblue
[Yellow Crystal] as YC
[Red Crystal] as RC3
[Green Crystal] as GC3
[Blue Crystal] as BC3
}
}

package Crusher #lightyellow {
[Crush Red Crystal] as CrR #lightblue
[Crush Green Crystal] as CrG #lightblue
[Crush Blue Crystal] as CrB #lightblue
}

SG ...> PA : 100
SM ...> PA : 100
SR ...> PA : 100
SC ...> PA : 100
SB ...> PA : 100
SY ...> PA : 100

W ..> SG : 100
W ..> SM : 100
W ..> SR : 100
W ..> SC : 100
W ..> SB : 100
W ..> SY : 100

C --> SG  : 1
SG --> GC1 : 1
SG --> MC : 1

C --> SR : 1
SR --> RC2 : 1
SR --> CC : 1

C --> SB : 1
SB --> BC3 : 1
SB --> YC : 1

YC --> SY : 1
SY --> RC3 : 1
SY --> GC3 : 1

CC --> SC : 1
SC --> GC2 : 1
SC --> BC2 : 1

MC --> SM : 1
SM --> BC1 : 1
SM --> RC1 : 1

RC1 --> RC : 1
RC2 --> RC : 1
RC3 --> RC : 1

GC1 --> GC : 1
GC2 --> GC : 1
GC3 --> GC : 1

BC1 --> BC : 1
BC2 --> BC : 1
BC3 --> BC : 1

BC --> CrB : 1
CrB --> CCr : 1

RC --> CrR : 1
CrR --> CCr : 1

GC --> CrG : 1
CrG --> CCr : 1



@enduml