@startuml

hide methods
hide fields
hide circle

[Crystal] as C1 #lightpink
[Crystal] as C2 #lightpink
[Crystal] as C3 #lightpink
[Ice] as I1 #lightpink
[Ice] as I2 #lightpink
[Ice] as I3 #lightpink


[Red Crystal] as RC #lightgreen
[Green Crystal] as GC #lightgreen
[Blue Crystal] as BC #lightgreen
[Crushed Crystal] as CCr #lightgreen

package Energizer #lightyellow {

package "Green Split Flow" {
[Split Green] as SG #lightblue
[Split Magenta] as SM #lightblue
[Magenta Crystal] as MC
[Water] as W1
[Red Crystal] as RC1 #lightgreen
[Green Crystal] as GC1 #lightgreen
[Blue Crystal] as BC1 #lightgreen
[Steam 165] as ST1 #lightgreen
}
package "Red Split Flow" {
[Split Red] as SR #lightblue
[Split Cyan] as SC #lightblue
[Cyan Crystal] as CC
[Water] as W2
[Red Crystal] as RC2 #lightgreen
[Green Crystal] as GC2 #lightgreen
[Blue Crystal] as BC2 #lightgreen
[Steam 165] as ST2 #lightgreen

}
package "Blue Split Flow" {
[Split Blue] as SB #lightblue
[Split Yellow] as SY #lightblue
[Yellow Crystal] as YC
[Water] as W3
[Red Crystal] as RC3 #lightgreen
[Green Crystal] as GC3 #lightgreen
[Blue Crystal] as BC3 #lightgreen
[Steam 165] as ST3 #lightgreen
}
}

package Crusher #lightyellow {
[Crush Red Crystal] as CrR #lightblue
[Crush Green Crystal] as CrG #lightblue
[Crush Blue Crystal] as CrB #lightblue
}

C1 --> SG : 4
I1 --> SG : 1
SG --> GC1 : 4
SG --> MC : 4
SG --> W1 : 20
MC --> SM : 1
W1 --> SM : 5
SM --> BC1 : 1
SM --> RC1 : 1
SM --> ST1 : 20

C2 --> SR : 4
I2 --> SR : 1
SR --> RC2 : 4
SR --> CC : 4
SR --> W2 : 20
CC --> SC : 1
W2 --> SC : 5
SC --> BC2 : 1
SC --> GC2 : 1
SC --> ST2 : 20

C3 --> SB : 4
I3 --> SB : 1
SB --> BC3 : 4
SB --> YC : 4
SB --> W3 : 20
YC --> SY : 1
W3 --> SY : 5
SY --> GC3 : 1
SY --> RC3 : 1
SY --> ST3 : 20

BC --> CrB : 3
CrB --> CCr : 1 (50%)

RC --> CrR : 3
CrR --> CCr : 1 (50%)

GC --> CrG : 3
CrG --> CCr : 1 (50%)



@enduml