@startuml

hide methods
hide fields
hide circle

[Red Crystal] as RC #lightpink
[Green Crystal] as GC #lightpink
[Blue Crystal] as BC #lightpink
[Crystal] as C #lightpink
[Water] as W1 #lightpink
[Water] as W2 #lightpink
[Water] as W3 #lightpink
[Water] as W4 #lightpink

[Iron Ore] as FE #lightgreen
[Copper Ore] as CU #lightgreen
[Stone] as S #lightgreen
[Coal] as Ca #lightgreen
[Steam 165] as PA1 #lightgreen
[Steam 165] as PA2 #lightgreen
[Steam 165] as PA3 #lightgreen
[Steam 165] as PA4 #lightgreen

[Neutralize] as NR #lightblue
[Neutralize] as NG #lightblue
[Neutralize] as NB #lightblue
[Neutralize] as NC #lightblue


RC --> NR : 1
GC --> NG : 1
BC --> NB : 1
C --> NC : 1

NR --> CU : 2
NG --> S : 2
NB --> FE : 2
NC --> Ca : 6

NR ..> PA1 : 20
NG ..> PA2 : 20
NB ..> PA3 : 20
NC ..> PA4 : 60

W1 ..> NR : 5
W2 ..> NG : 5
W3 ..> NB : 5
W4 ..> NC : 15
@enduml