@startuml

hide methods
hide fields
hide circle

[Crystal Ore] as CO #lightpink
[Crushed Crystal] as CCr
[Crystal Slurry] as CS
[Ice] as I #lightpink
[Water] as W

[Crystal] as C #lightgreen

package "Chemical Plant" #lightyellow {
[Melt 1s] as Me #lightblue
[Sludge from Crushed Crystal 1s] as SCS #lightblue
[Crystalise 4s] as CCF #lightblue
}

package "Crusher" #lightyellow {
[Crush Crystal Ore 1s] as Cr #lightblue
}



CO --> Cr : 1
Cr --> CCr : 2
CCr --> SCS : 15
I --> Me : 1
Me --> W : 20
W --> SCS : 20
SCS --> CS : 20
CS --> CCF : 16
CCF --> C : 75% 8
CCF --> CCr : 25% 2





@enduml