@startuml

hide methods
hide fields
hide circle

[Water] as W1 #lightpink
[Water] as W2 #lightpink
[Water] as W3 #lightpink

[Red Crystal] as RC #lightpink
[Blue Crystal] as BC #lightpink
[Green Crystal] as GC #lightpink

[Red Sludge] as RS
[Green Sludge] as GS
[Blue Sludge] as BS

[Purple Mixture] as PM
[Yellow Mixture] as YM

[Heavy Oil] as HO #lightgreen
[Light Oil] as LO #lightgreen
[Gas] as G #lightgreen
[Lubricant] as L #lightgreen
[Steam 165] as PA1 #lightgreen
[Steam 165] as PA2 #lightgreen
[Steam 165] as PA3 #lightgreen
[Steam 165] as PA4 #lightgreen

[Sludge from Red Crystal] as SfR #lightblue
[Sludge from Blue Crystal]as SfB #lightblue
[Sludge from Green Crystal]as SfG #lightblue
[Purple Mix] as CPB #lightblue
[Yellow Mix] as CPY #lightblue

[Denaturize] as HOP #lightblue
[Denaturize] as LOP #lightblue
[Denaturize] as GP #lightblue
[Denaturize] as LP #lightblue


RC --> SfR : 5
W1 --> SfR : 20
SfR --> RS : 20

BC --> SfB : 10
W2 --> SfB : 20
SfB  --> BS : 20

GC --> SfG : 10
W3 --> SfG : 20
SfG --> GS : 20

RS --> CPB : 5
BS --> CPB : 5
CPB --> PM : 5
PM --> GP : 20
GP --> G : 20

RS ----> HOP : 20
HOP --> HO : 20

GS --> CPY : 5
RS --> CPY : 5
CPY --> YM : 5
YM --> LOP : 20
LOP --> LO : 20

GS ----> LP : 20
LP --> L : 20

HOP ..> PA1 : 80
LOP ..> PA2 : 08
GP ..> PA3 : 80
LP ..> PA4 : 08


@enduml