@startuml

hide methods
hide fields
hide circle

[Ice] as I #lightpink
[Water] as W

[Red Crystal] as RC #lightpink
[Blue Crystal] as BC #lightpink
[Green Crystal] as GC #lightpink

[Red Sludge] as RS
[Green Sludge] as GS
[Blue Sludge] as BS

[Purple Mixture] as PM
[Yellow Mixture] as YM

[Heavy Oil] as HO #lightgreen
[Light Oil] as LO #lightgreen
[Gas] as G #lightgreen
[Lubricant] as L #lightgreen
[Plasma] as PA #lightgreen

package "Crystalizer" #lightyellow {
[Sludge from Red Crystal] as SfR #lightblue
[Sludge from Blue Crystal]as SfB #lightblue
[Sludge from Green Crystal]as SfG #lightblue
}

package "Chemical Plant" #lightyellow {
[Purple Mix] as CPB #lightblue
[Yellow Mix] as CPY #lightblue
[Melt] as Me #lightblue
}


package Energizer #lightyellow {
[Denaturize] as HOP #lightblue
[Denaturize] as LOP #lightblue
[Denaturize] as GP #lightblue
[Denaturize] as LP #lightblue
}

I --> Me : 1
Me --> W : 20

RC --> SfR : 5
W --> SfR : 20
SfR --> RS : 20

BC --> SfB : 10
W --> SfB : 20
SfB  --> BS : 20

GC --> SfG : 10
W --> SfG : 20
SfG --> GS : 20

RS --> CPB : 5
BS --> CPB : 5
CPB --> PM : 5
PM --> GP : 20
GP --> G : 20

RS --> HOP : 20
HOP --> HO : 20

GS --> CPY : 5
RS --> CPY : 5
CPY --> YM : 5
YM --> LOP : 20
LOP --> LO : 20

GS --> LP : 20
LP --> L : 20

HOP ...> PA : 100
LOP ...> PA : 100
GP ...> PA : 100
LP ...> PA : 100

@enduml