@startuml
hide methods
hide fields
hide circle
[crystarion_condensation_rod_medium] AS rec_crystarion_condensation_rod_medium_S0 #lightblue
[crystarion_crystal_green] AS crystarion_crystal_green_S0
[ice] AS ice_S0
[crystarion_condensation_rod_medium] AS crystarion_condensation_rod_medium_S0
crystarion_crystal_green_S0 --> rec_crystarion_condensation_rod_medium_S0
ice_S0 --> rec_crystarion_condensation_rod_medium_S0
rec_crystarion_condensation_rod_medium_S0 --> crystarion_condensation_rod_medium_S0

[crystarion_condensation_rod_big] AS rec_crystarion_condensation_rod_big_S1 #lightblue
[crystarion_crystal_yellow] AS crystarion_crystal_yellow_S1
[ice] AS ice_S1
[crystarion_condensation_rod_big] AS crystarion_condensation_rod_big_S1
crystarion_crystal_yellow_S1 --> rec_crystarion_condensation_rod_big_S1
ice_S1 --> rec_crystarion_condensation_rod_big_S1
rec_crystarion_condensation_rod_big_S1 --> crystarion_condensation_rod_big_S1

[crystarion_condensation_rod_huge] AS rec_crystarion_condensation_rod_huge_S2 #lightblue
[crystarion_crystal] AS crystarion_crystal_S2
[ice] AS ice_S2
[crystarion_condensation_rod_huge] AS crystarion_condensation_rod_huge_S2
crystarion_crystal_S2 --> rec_crystarion_condensation_rod_huge_S2
ice_S2 --> rec_crystarion_condensation_rod_huge_S2
rec_crystarion_condensation_rod_huge_S2 --> crystarion_condensation_rod_huge_S2

[crystarion_accumulator] AS rec_crystarion_accumulator_S3 #lightblue
[iron_plate] AS iron_plate_S3
[battery] AS battery_S3
[crystarion_crystal] AS crystarion_crystal_S3
[crystarion_accumulator] AS crystarion_accumulator_S3
iron_plate_S3 --> rec_crystarion_accumulator_S3
battery_S3 --> rec_crystarion_accumulator_S3
crystarion_crystal_S3 --> rec_crystarion_accumulator_S3
rec_crystarion_accumulator_S3 --> crystarion_accumulator_S3

[crystarion_crusher] AS rec_crystarion_crusher_S4 #lightblue
[iron_gear_wheel] AS iron_gear_wheel_S4
[iron_plate] AS iron_plate_S4
[crystarion_crusher] AS crystarion_crusher_S4
iron_gear_wheel_S4 --> rec_crystarion_crusher_S4
iron_plate_S4 --> rec_crystarion_crusher_S4
rec_crystarion_crusher_S4 --> crystarion_crusher_S4

[crystarion_empowerer] AS rec_crystarion_empowerer_S5 #lightblue
[iron_gear_wheel] AS iron_gear_wheel_S5
[iron_plate] AS iron_plate_S5
[crystarion_empowerer] AS crystarion_empowerer_S5
iron_gear_wheel_S5 --> rec_crystarion_empowerer_S5
iron_plate_S5 --> rec_crystarion_empowerer_S5
rec_crystarion_empowerer_S5 --> crystarion_empowerer_S5

[crystarion_energiser] AS rec_crystarion_energiser_S6 #lightblue
[iron_plate] AS iron_plate_S6
[copper_plate] AS copper_plate_S6
[copper_cable] AS copper_cable_S6
[battery] AS battery_S6
[crystarion_crystal] AS crystarion_crystal_S6
[crystarion_energiser] AS crystarion_energiser_S6
iron_plate_S6 --> rec_crystarion_energiser_S6
copper_plate_S6 --> rec_crystarion_energiser_S6
copper_cable_S6 --> rec_crystarion_energiser_S6
battery_S6 --> rec_crystarion_energiser_S6
crystarion_crystal_S6 --> rec_crystarion_energiser_S6
rec_crystarion_energiser_S6 --> crystarion_energiser_S6

[crystarion_lure] AS rec_crystarion_lure_L #lightblue
[copper_plate] AS copper_plate_L
[copper_cable] AS copper_cable_L
[electronic_circuit] AS electronic_circuit_L
[battery] AS battery_L
[crystarion_lure] AS crystarion_lure_L
copper_plate_L --> rec_crystarion_lure_L
copper_cable_L --> rec_crystarion_lure_L
electronic_circuit_L --> rec_crystarion_lure_L
battery_L --> rec_crystarion_lure_L
rec_crystarion_lure_L --> crystarion_lure_L

[crystarion_lure_big] AS rec_crystarion_lure_big_L #lightblue
[copper_cable] AS copper_cable_L
[crystarion_lure] AS crystarion_lure_L
[crystarion_lure_big] AS crystarion_lure_big_L
copper_cable_L --> rec_crystarion_lure_big_L
crystarion_lure_L --> rec_crystarion_lure_big_L
rec_crystarion_lure_big_L --> crystarion_lure_big_L

[crystarion_naturizer] AS rec_crystarion_naturizer_S7 #lightblue
[iron_plate] AS iron_plate_S7
[crystarion_crystal] AS crystarion_crystal_S7
[crystarion_naturizer] AS crystarion_naturizer_S7
iron_plate_S7 --> rec_crystarion_naturizer_S7
crystarion_crystal_S7 --> rec_crystarion_naturizer_S7
rec_crystarion_naturizer_S7 --> crystarion_naturizer_S7

[crystarion_collector] AS rec_crystarion_collector_S8 #lightblue
[iron_plate] AS iron_plate_S8
[copper_plate] AS copper_plate_S8
[electronic_circuit] AS electronic_circuit_S8
[battery] AS battery_S8
[crystarion_crystal] AS crystarion_crystal_S8
[crystarion_collector] AS crystarion_collector_S8
iron_plate_S8 --> rec_crystarion_collector_S8
copper_plate_S8 --> rec_crystarion_collector_S8
electronic_circuit_S8 --> rec_crystarion_collector_S8
battery_S8 --> rec_crystarion_collector_S8
crystarion_crystal_S8 --> rec_crystarion_collector_S8
rec_crystarion_collector_S8 --> crystarion_collector_S8

[crystarion_crystal_ammo] AS rec_crystarion_crystal_ammo_M #lightblue
[crystarion_crystal_splinter] AS crystarion_crystal_splinter_M
[crystarion_crystal_ammo] AS crystarion_crystal_ammo_M
crystarion_crystal_splinter_M --> rec_crystarion_crystal_ammo_M
rec_crystarion_crystal_ammo_M --> crystarion_crystal_ammo_M

[crystarion_land_mine] AS rec_crystarion_land_mine_M #lightblue
[crystarion_crystal_splinter] AS crystarion_crystal_splinter_M
[crystarion_land_mine] AS crystarion_land_mine_M
crystarion_crystal_splinter_M --> rec_crystarion_land_mine_M
rec_crystarion_land_mine_M --> crystarion_land_mine_M

[crystarion_battery] AS rec_crystarion_battery_S9 #lightblue
[crystarion_crystal] AS crystarion_crystal_S9
[iron_plate] AS iron_plate_S9
[copper_plate] AS copper_plate_S9
[battery] AS battery_S9
crystarion_crystal_S9 --> rec_crystarion_battery_S9
iron_plate_S9 --> rec_crystarion_battery_S9
copper_plate_S9 --> rec_crystarion_battery_S9
rec_crystarion_battery_S9 --> battery_S9

[crystarion_sludge_from_crushed_crystal] AS rec_crystarion_sludge_from_crushed_crystal_1 #lightblue
[water] AS water_1
[crystarion_crushed_crystal] AS crystarion_crushed_crystal_1
[crystarion_crystal_slurry] AS crystarion_crystal_slurry_1
water_1 --> rec_crystarion_sludge_from_crushed_crystal_1
crystarion_crushed_crystal_1 --> rec_crystarion_sludge_from_crushed_crystal_1
rec_crystarion_sludge_from_crushed_crystal_1 --> crystarion_crystal_slurry_1

[crystarion_crush_crystal_ore] AS rec_crystarion_crush_crystal_ore_1 #lightblue
[crystarion_crystal_ore] AS crystarion_crystal_ore_1
[crystarion_crushed_crystal] AS crystarion_crushed_crystal_1
crystarion_crystal_ore_1 --> rec_crystarion_crush_crystal_ore_1
rec_crystarion_crush_crystal_ore_1 --> crystarion_crushed_crystal_1

[crystarion_crystal_ore_splinter] AS rec_crystarion_crystal_ore_splinter_M #lightblue
[crystarion_crystal] AS crystarion_crystal_M
[crystarion_crystal_splinter] AS crystarion_crystal_splinter_M
crystarion_crystal_M --> rec_crystarion_crystal_ore_splinter_M
rec_crystarion_crystal_ore_splinter_M --> crystarion_crystal_splinter_M

[crystarion_crystal_ore_splinter_less] AS rec_crystarion_crystal_ore_splinter_less_M #lightblue
[crystarion_crushed_crystal] AS crystarion_crushed_crystal_M
[crystarion_crystal_splinter] AS crystarion_crystal_splinter_M
crystarion_crushed_crystal_M --> rec_crystarion_crystal_ore_splinter_less_M
rec_crystarion_crystal_ore_splinter_less_M --> crystarion_crystal_splinter_M

[crystarion_crystalise] AS rec_crystarion_crystalise_1 #lightblue
[crystarion_crystal_slurry] AS crystarion_crystal_slurry_1
[crystarion_crystal] AS crystarion_crystal_1
[crystarion_crushed_crystal] AS crystarion_crushed_crystal_1
crystarion_crystal_slurry_1 --> rec_crystarion_crystalise_1
rec_crystarion_crystalise_1 --> crystarion_crystal_1
rec_crystarion_crystalise_1 --> crystarion_crushed_crystal_1

[crystarion_revitalise_coal] AS rec_crystarion_revitalise_coal_3 #lightblue
[crystarion_crystal] AS crystarion_crystal_3
[coal] AS coal_3
[water] AS water_3
[wood] AS wood_3
[steam] AS steam_3
crystarion_crystal_3 --> rec_crystarion_revitalise_coal_3
coal_3 --> rec_crystarion_revitalise_coal_3
water_3 --> rec_crystarion_revitalise_coal_3
rec_crystarion_revitalise_coal_3 --> wood_3
rec_crystarion_revitalise_coal_3 --> steam_3

[crystarion_slurry_from_red_crystal] AS rec_crystarion_slurry_from_red_crystal_2 #lightblue
[crystarion_crystal_red] AS crystarion_crystal_red_2
[water] AS water_2
[crystarion_red_slurry] AS crystarion_red_slurry_2
crystarion_crystal_red_2 --> rec_crystarion_slurry_from_red_crystal_2
water_2 --> rec_crystarion_slurry_from_red_crystal_2
rec_crystarion_slurry_from_red_crystal_2 --> crystarion_red_slurry_2

[crystarion_denaturize_yellow] AS rec_crystarion_denaturize_yellow_2 #lightblue
[crystarion_yellow_mixture] AS crystarion_yellow_mixture_2
[light_oil] AS light_oil_2
[crystarion_crystal_splinter_volatile] AS crystarion_crystal_splinter_volatile_2
crystarion_yellow_mixture_2 --> rec_crystarion_denaturize_yellow_2
rec_crystarion_denaturize_yellow_2 --> light_oil_2
rec_crystarion_denaturize_yellow_2 --> crystarion_crystal_splinter_volatile_2

[crystarion_denaturize_purple] AS rec_crystarion_denaturize_purple_2 #lightblue
[crystarion_purple_mixture] AS crystarion_purple_mixture_2
[petroleum_gas] AS petroleum_gas_2
[crystarion_crystal_splinter_volatile] AS crystarion_crystal_splinter_volatile_2
crystarion_purple_mixture_2 --> rec_crystarion_denaturize_purple_2
rec_crystarion_denaturize_purple_2 --> petroleum_gas_2
rec_crystarion_denaturize_purple_2 --> crystarion_crystal_splinter_volatile_2

[crystarion_denaturize_red] AS rec_crystarion_denaturize_red_2 #lightblue
[crystarion_red_slurry] AS crystarion_red_slurry_2
[heavy_oil] AS heavy_oil_2
[crystarion_crystal_splinter_volatile] AS crystarion_crystal_splinter_volatile_2
crystarion_red_slurry_2 --> rec_crystarion_denaturize_red_2
rec_crystarion_denaturize_red_2 --> heavy_oil_2
rec_crystarion_denaturize_red_2 --> crystarion_crystal_splinter_volatile_2

[crystarion_denaturize_green] AS rec_crystarion_denaturize_green_2 #lightblue
[crystarion_green_slurry] AS crystarion_green_slurry_2
[lubricant] AS lubricant_2
[crystarion_crystal_splinter_volatile] AS crystarion_crystal_splinter_volatile_2
crystarion_green_slurry_2 --> rec_crystarion_denaturize_green_2
rec_crystarion_denaturize_green_2 --> lubricant_2
rec_crystarion_denaturize_green_2 --> crystarion_crystal_splinter_volatile_2

[crystarion_create_slurry] AS rec_crystarion_create_slurry_2 #lightblue
[crystarion_crystal_red] AS crystarion_crystal_red_2
[crystarion_crystal_green] AS crystarion_crystal_green_2
[crystarion_crystal_blue] AS crystarion_crystal_blue_2
[water] AS water_2
[crystarion_red_slurry] AS crystarion_red_slurry_2
[crystarion_green_slurry] AS crystarion_green_slurry_2
[crystarion_blue_slurry] AS crystarion_blue_slurry_2
crystarion_crystal_red_2 --> rec_crystarion_create_slurry_2
crystarion_crystal_green_2 --> rec_crystarion_create_slurry_2
crystarion_crystal_blue_2 --> rec_crystarion_create_slurry_2
water_2 --> rec_crystarion_create_slurry_2
rec_crystarion_create_slurry_2 --> crystarion_red_slurry_2
rec_crystarion_create_slurry_2 --> crystarion_green_slurry_2
rec_crystarion_create_slurry_2 --> crystarion_blue_slurry_2

[crystarion_mix_yellow] AS rec_crystarion_mix_yellow_2 #lightblue
[crystarion_green_slurry] AS crystarion_green_slurry_2
[crystarion_red_slurry] AS crystarion_red_slurry_2
[crystarion_yellow_mixture] AS crystarion_yellow_mixture_2
crystarion_green_slurry_2 --> rec_crystarion_mix_yellow_2
crystarion_red_slurry_2 --> rec_crystarion_mix_yellow_2
rec_crystarion_mix_yellow_2 --> crystarion_yellow_mixture_2

[crystarion_mix_purple] AS rec_crystarion_mix_purple_2 #lightblue
[crystarion_blue_slurry] AS crystarion_blue_slurry_2
[crystarion_red_slurry] AS crystarion_red_slurry_2
[crystarion_purple_mixture] AS crystarion_purple_mixture_2
crystarion_blue_slurry_2 --> rec_crystarion_mix_purple_2
crystarion_red_slurry_2 --> rec_crystarion_mix_purple_2
rec_crystarion_mix_purple_2 --> crystarion_purple_mixture_2

[crystarion_crystalise_purple] AS rec_crystarion_crystalise_purple_2 #lightblue
[crystarion_purple_mixture] AS crystarion_purple_mixture_2
[crystarion_crystal_magenta] AS crystarion_crystal_magenta_2
[steam] AS steam_2
[petroleum_gas] AS petroleum_gas_2
crystarion_purple_mixture_2 --> rec_crystarion_crystalise_purple_2
rec_crystarion_crystalise_purple_2 --> crystarion_crystal_magenta_2
rec_crystarion_crystalise_purple_2 --> steam_2
rec_crystarion_crystalise_purple_2 --> petroleum_gas_2

[crystarion_crush_crystal_red] AS rec_crystarion_crush_crystal_red_3 #lightblue
[crystarion_crystal_red] AS crystarion_crystal_red_3
[crystarion_crushed_crystal] AS crystarion_crushed_crystal_3
crystarion_crystal_red_3 --> rec_crystarion_crush_crystal_red_3
rec_crystarion_crush_crystal_red_3 --> crystarion_crushed_crystal_3

[crystarion_crush_crystal_green] AS rec_crystarion_crush_crystal_green_3 #lightblue
[crystarion_crystal_green] AS crystarion_crystal_green_3
[crystarion_crushed_crystal] AS crystarion_crushed_crystal_3
crystarion_crystal_green_3 --> rec_crystarion_crush_crystal_green_3
rec_crystarion_crush_crystal_green_3 --> crystarion_crushed_crystal_3

[crystarion_crush_crystal_blue] AS rec_crystarion_crush_crystal_blue_3 #lightblue
[crystarion_crystal_blue] AS crystarion_crystal_blue_3
[crystarion_crushed_crystal] AS crystarion_crushed_crystal_3
crystarion_crystal_blue_3 --> rec_crystarion_crush_crystal_blue_3
rec_crystarion_crush_crystal_blue_3 --> crystarion_crushed_crystal_3

[crystarion_crush_crystal_yellow] AS rec_crystarion_crush_crystal_yellow_3 #lightblue
[crystarion_crystal_yellow] AS crystarion_crystal_yellow_3
[crystarion_crushed_crystal] AS crystarion_crushed_crystal_3
crystarion_crystal_yellow_3 --> rec_crystarion_crush_crystal_yellow_3
rec_crystarion_crush_crystal_yellow_3 --> crystarion_crushed_crystal_3

[crystarion_crush_crystal_magenta] AS rec_crystarion_crush_crystal_magenta_3 #lightblue
[crystarion_crystal_magenta] AS crystarion_crystal_magenta_3
[crystarion_crushed_crystal] AS crystarion_crushed_crystal_3
crystarion_crystal_magenta_3 --> rec_crystarion_crush_crystal_magenta_3
rec_crystarion_crush_crystal_magenta_3 --> crystarion_crushed_crystal_3

[crystarion_neutralize_red] AS rec_crystarion_neutralize_red_3 #lightblue
[crystarion_crystal_red] AS crystarion_crystal_red_3
[water] AS water_3
[copper_ore] AS copper_ore_3
[steam] AS steam_3
crystarion_crystal_red_3 --> rec_crystarion_neutralize_red_3
water_3 --> rec_crystarion_neutralize_red_3
rec_crystarion_neutralize_red_3 --> copper_ore_3
rec_crystarion_neutralize_red_3 --> steam_3

[crystarion_neutralize_green] AS rec_crystarion_neutralize_green_3 #lightblue
[crystarion_crystal_green] AS crystarion_crystal_green_3
[water] AS water_3
[stone] AS stone_3
[steam] AS steam_3
crystarion_crystal_green_3 --> rec_crystarion_neutralize_green_3
water_3 --> rec_crystarion_neutralize_green_3
rec_crystarion_neutralize_green_3 --> stone_3
rec_crystarion_neutralize_green_3 --> steam_3

[crystarion_neutralize_blue] AS rec_crystarion_neutralize_blue_3 #lightblue
[crystarion_crystal_blue] AS crystarion_crystal_blue_3
[water] AS water_3
[iron_ore] AS iron_ore_3
[steam] AS steam_3
crystarion_crystal_blue_3 --> rec_crystarion_neutralize_blue_3
water_3 --> rec_crystarion_neutralize_blue_3
rec_crystarion_neutralize_blue_3 --> iron_ore_3
rec_crystarion_neutralize_blue_3 --> steam_3

[crystarion_neutralize_crystal] AS rec_crystarion_neutralize_crystal_3 #lightblue
[crystarion_crystal] AS crystarion_crystal_3
[water] AS water_3
[coal] AS coal_3
[steam] AS steam_3
crystarion_crystal_3 --> rec_crystarion_neutralize_crystal_3
water_3 --> rec_crystarion_neutralize_crystal_3
rec_crystarion_neutralize_crystal_3 --> coal_3
rec_crystarion_neutralize_crystal_3 --> steam_3

[crystarion_split_blue] AS rec_crystarion_split_blue_3 #lightblue
[crystarion_crystal] AS crystarion_crystal_3
[ice] AS ice_3
[crystarion_crystal_blue] AS crystarion_crystal_blue_3
[crystarion_crystal_yellow] AS crystarion_crystal_yellow_3
[water] AS water_3
crystarion_crystal_3 --> rec_crystarion_split_blue_3
ice_3 --> rec_crystarion_split_blue_3
rec_crystarion_split_blue_3 --> crystarion_crystal_blue_3
rec_crystarion_split_blue_3 --> crystarion_crystal_yellow_3
rec_crystarion_split_blue_3 --> water_3

[crystarion_split_yellow] AS rec_crystarion_split_yellow_3 #lightblue
[crystarion_crystal_yellow] AS crystarion_crystal_yellow_3
[water] AS water_3
[crystarion_crystal_green] AS crystarion_crystal_green_3
[crystarion_crystal_red] AS crystarion_crystal_red_3
[steam] AS steam_3
crystarion_crystal_yellow_3 --> rec_crystarion_split_yellow_3
water_3 --> rec_crystarion_split_yellow_3
rec_crystarion_split_yellow_3 --> crystarion_crystal_green_3
rec_crystarion_split_yellow_3 --> crystarion_crystal_red_3
rec_crystarion_split_yellow_3 --> steam_3

[crystarion_crystal_empower_1] AS rec_crystarion_crystal_empower_1_4 #lightblue
[crystarion_crystal] AS crystarion_crystal_4
[crystarion_crystal_volatile] AS crystarion_crystal_volatile_4
crystarion_crystal_4 --> rec_crystarion_crystal_empower_1_4
rec_crystarion_crystal_empower_1_4 --> crystarion_crystal_volatile_4

[crystarion_crystal_empower_2] AS rec_crystarion_crystal_empower_2_4 #lightblue
[crystarion_crystal] AS crystarion_crystal_4
[crystarion_crystal_yellow] AS crystarion_crystal_yellow_4
[crystarion_crystal_unstable] AS crystarion_crystal_unstable_4
crystarion_crystal_4 --> rec_crystarion_crystal_empower_2_4
crystarion_crystal_yellow_4 --> rec_crystarion_crystal_empower_2_4
rec_crystarion_crystal_empower_2_4 --> crystarion_crystal_unstable_4

[crystarion_crystal_empower_3] AS rec_crystarion_crystal_empower_3_4 #lightblue
[crystarion_crystal] AS crystarion_crystal_4
[crystarion_crystal_yellow] AS crystarion_crystal_yellow_4
[crystarion_crystal_magenta] AS crystarion_crystal_magenta_4
[crystarion_crystal_stable] AS crystarion_crystal_stable_4
crystarion_crystal_4 --> rec_crystarion_crystal_empower_3_4
crystarion_crystal_yellow_4 --> rec_crystarion_crystal_empower_3_4
crystarion_crystal_magenta_4 --> rec_crystarion_crystal_empower_3_4
rec_crystarion_crystal_empower_3_4 --> crystarion_crystal_stable_4

[crystarion_science] AS rec_crystarion_science_4 #lightblue
[crystarion_crystal] AS crystarion_crystal_4
[crystarion_crystal_volatile] AS crystarion_crystal_volatile_4
[crystarion_crystal_unstable] AS crystarion_crystal_unstable_4
[crystarion_crystal_stable] AS crystarion_crystal_stable_4
[crystarion_science] AS crystarion_science_4
crystarion_crystal_4 --> rec_crystarion_science_4
crystarion_crystal_volatile_4 --> rec_crystarion_science_4
crystarion_crystal_unstable_4 --> rec_crystarion_science_4
crystarion_crystal_stable_4 --> rec_crystarion_science_4
rec_crystarion_science_4 --> crystarion_science_4

@enduml
