@startuml

hide methods
hide fields
hide circle

[Crystal Ore] as CO #lightpink
[Crushed Crystal] as CCr
[Crystal Slurry] as CS
[Ice] as I #lightpink
[Water] as W

[Crystal] as C

[Red Crystal] as RC #lightgreen
[Green Crystal] as GC #lightgreen
[Blue Crystal] as BC #lightgreen

[Red Mixture] as RM
[Purple Mixture] as PM
[Crystaline Mixture] as CM

[Heavy Oil] as HO #lightgreen
[Light Oil] as LO #lightgreen
[Gas] as G #lightgreen

[Iron Ore] as FE #lightgreen
[Copper Ore] as CU #lightgreen
[Stone] as S #lightgreen

[Energy] as E #teal

package Splitter #lightyellow {
package "Green Split Flow" {
[Split Green] as SG #lightblue
[Split Magenta] as SM #lightblue
[Magenta Crystal] as MC
[Red Crystal] as RC1
[Green Crystal] as GC1
[Blue Crystal] as BC1
}
package "Red Split Flow" {
[Split Red] as SR #lightblue
[Split Cyan] as SC #lightblue
[Cyan Crystal] as CC
[Red Crystal] as RC2
[Green Crystal] as GC2
[Blue Crystal] as BC2

}
package "Blue Split Flow" {
[Split Blue] as SB #lightblue
[Split Yellow] as SY #lightblue
[Yellow Crystal] as YC
[Red Crystal] as RC3
[Green Crystal] as GC3
[Blue Crystal] as BC3
}
}
package Energizer #lightyellow {
[Neutralize] as NR #lightblue
[Neutralize] as NG #lightblue
[Neutralize] as NB #lightblue
}
package "Chemical Plant" #lightyellow {
[Sludge from Crushed Crystal] as SCS #lightblue
[Melt] as Me #lightblue
}

package Crusher #lightyellow {
[Crush Crystal Ore] as Cr #lightblue
}

package Crystalizer #lightyellow {
[Crystalise] as CCF #lightblue
}
package "Chemical Plant" #lightyellow {
[Red Mix] as CPR #lightblue
[Purple Mix] as CPB #lightblue
[Full Mix] as CPG #lightblue
[Melt] as Me #lightblue
}

package Energizer #lightyellow {
[Denaturize] as HOP #lightblue
[Denaturize] as LOP #lightblue
[Denaturize] as GP #lightblue
}
package "Chemical Plant" #lightyellow {
[Red Mix] as CPR #lightblue
[Purple Mix] as CPB #lightblue
[Full Mix] as CPG #lightblue
[Melt] as Me #lightblue
}

package Energizer #lightyellow {
[Denaturize] as HOP #lightblue
[Denaturize] as LOP #lightblue
[Denaturize] as GP #lightblue
}
package Energizer #lightyellow {
[Extract] as DE #lightblue
}
C --> SG
SG --> GC1
SG --> MC

C --> SR
SR --> RC2
SR --> CC

C --> SB
SB --> BC3
SB --> YC

YC --> SY
SY --> RC3
SY --> GC3

CC --> SC
SC --> GC2
SC --> BC2

MC --> SM
SM --> BC1
SM --> RC1

RC1 --> RC
RC2 --> RC
RC3 --> RC

GC1 --> GC
GC2 --> GC
GC3 --> GC

BC1 --> BC
BC2 --> BC
BC3 --> BC
RC --> NR
GC --> NG
BC --> NB

NR --> CU
NG --> S
NB --> FE
CO --> Cr
Cr --> CCr
CCr --> SCS
I --> Me
Me --> W
W --> SCS
SCS --> CS
CS --> CCF
CCF --> C : 75% with quality
CCF --> CCr : 25%

W --> CPR
RC --> CPR
CPR --> RM

RM --> CPB
BC --> CPB
CPB --> PM

PM --> CPG
GC --> CPG
CPG --> CM

RM --> HOP
HOP --> HO

PM --> LOP
LOP --> LO

CM --> GP
GP --> G

C --> DE
DE --> CCr
Energizer --> E
Splitter --> E
Energizer <-- E
Splitter <-- E

@enduml