@startuml

hide methods
hide fields
hide circle


[Crystal] as C1 #lightpink
[Crystal] as C2 #lightpink
[Crystal] as C3 #lightpink
[Yellow Crystal] as YC1 #lightpink
[Yellow Crystal] as YC2 #lightpink
[Purple Crystal] as PCr

[Power] as P1 #lightpink
[Power] as P2 #lightpink
[Power] as P3 #lightpink

[Purple Mix] as CPB #lightpink

package "Empowerer" #lightyellow {
    [Empower 1s] as EMP1 #lightblue
    [Empower 2s] as EMP2 #lightblue
    [Empower 5s] as EMP3 #lightblue
}

[Crystalise] as CR #lightblue

[Volatile Powercrystal] as VPC
[Unstable Powercrystal] as UPC
[Stable Powercrystal] as SPC

[Create] as Cr1 #lightblue

[Unstable Crystal Science] as S #lightgreen

CPB --> CR
CR --> PCr

C1 ----> EMP1 : 15
C2 ----> EMP2 : 30
YC1 ----> EMP2 : 30
YC2 ----> EMP3 : 60
C3 ----> EMP3 : 60
PCr --> EMP3 : 60

P1 ----> EMP1 : 100 MW
P2 ----> EMP2 : 200 MW
P3 ----> EMP3 : 500 MW

EMP1 --> VPC : 15
EMP2 --> UPC : 30
EMP3 --> SPC : 60

VPC --> Cr1
UPC --> Cr1
SPC --> Cr1
Cr1 --> S

@enduml